/**
 * CodingStandardsEnforcer Contract — Block ALL TypeScript that violates coding standards.
 *
 * PreToolUse hook that fires on Edit and Write operations targeting
 * ANY .ts/.tsx file. Scans the FULL FILE content for violations:
 *   1. Raw Node builtin imports (fs, child_process, http, crypto)
 *   2. Try-catch used for flow control (should use explicit error handling)
 *   3. Hardcoded environment variable access (should inject via configuration)
 *
 * For Edit operations: reads the current file from disk, applies the edit,
 * then checks the ENTIRE resulting file. This prevents surgical edits from
 * bypassing enforcement on files with existing violations.
 *
 * Excludes adapter files (any adapters/ directory or adapter(s).ts files)
 * which legitimately wrap builtins.
 *
 * Logs all blocked violations to MEMORY/LEARNING/SIGNALS/coding-standards-violations.jsonl
 * for pattern analysis.
 */

import type { HookContract } from "@hooks/core/contract";
import type { ToolHookInput } from "@hooks/core/types/hook-inputs";
import type { ContinueOutput, BlockOutput } from "@hooks/core/types/hook-outputs";
import { ok, type Result } from "@hooks/core/result";
import type { PaiError } from "@hooks/core/error";
import { readFile as adapterReadFile } from "@hooks/core/adapters/fs";
import {
  type Violation,
  findAllViolations,
  isTypeScriptFile,
  isAdapterFile,
  isAutoGeneratedFile,
  isSkippedFilename,
} from "@hooks/lib/coding-standards-checks";
import { logSignal, defaultSignalLoggerDeps, type SignalLoggerDeps } from "@hooks/lib/signal-logger";
import { pickNarrative } from "@hooks/lib/narrative-reader";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface CodingStandardsEnforcerDeps {
  readFile: (path: string) => string | null;
  signal: SignalLoggerDeps;
  stderr: (msg: string) => void;
}

// ─── Pure Functions ──────────────────────────────────────────────────────────

function getFilePath(input: ToolHookInput): string | null {
  if (typeof input.tool_input !== "object" || input.tool_input === null) return null;
  return (input.tool_input.file_path as string) ?? null;
}

/** For Write: returns the full file content. For Edit: returns null (handled separately). */
function getWriteContent(input: ToolHookInput): string | null {
  if (typeof input.tool_input !== "object" || input.tool_input === null) return null;
  if (input.tool_name === "Write") return (input.tool_input.content as string) ?? null;
  return null;
}

/** For Edit: get old_string and new_string to simulate the edit on the full file. */
function getEditParts(input: ToolHookInput): { oldStr: string; newStr: string } | null {
  if (typeof input.tool_input !== "object" || input.tool_input === null) return null;
  if (input.tool_name !== "Edit") return null;
  const oldStr = input.tool_input.old_string as string | undefined;
  const newStr = input.tool_input.new_string as string | undefined;
  if (!oldStr || !newStr) return null;
  return { oldStr, newStr };
}

/** Simulate an Edit by applying the replacement to the full file content. */
function applyEdit(fileContent: string, oldStr: string, newStr: string): string {
  return fileContent.replace(oldStr, newStr);
}

function formatBlockMessage(violations: Violation[], filePath: string): string {
  const grouped: Record<string, Violation[]> = {};
  for (const v of violations) {
    (grouped[v.category] ??= []).push(v);
  }

  const opener = pickNarrative("CodingStandardsEnforcer", violations.length);
  const sections: string[] = [
    opener,
    "",
    `${violations.length} violation${violations.length === 1 ? "" : "s"} in ${filePath}:`,
    "",
  ];

  const categoryLabels: Record<string, string> = {
    "raw-import": "Raw Node builtin imports (use an adapters/ wrapper instead):",
    "try-catch": "Try-catch flow control (use explicit error returns instead):",
    "process-env": "Direct env access (inject via Deps + defaultDeps):",
    "inline-import-type": "Inline import types (use top-level import type declarations):",
    "as-any": "Unsafe type casts (use proper types or unknown intermediate):",
    "relative-import": "Relative imports (use non-relative path aliases):",
  };

  for (const [category, label] of Object.entries(categoryLabels)) {
    const items = grouped[category];
    if (items?.length) {
      sections.push(label);
      for (const v of items) {
        sections.push(`  Line ${v.line}: ${v.content}`);
      }
      sections.push("");
    }
  }

  const fixMap: Record<string, string> = {
    "raw-import": "Wrap I/O behind injectable dependencies (not raw Node builtins)",
    "try-catch": "Use explicit error returns (not try-catch for flow control)",
    "process-env": "Inject environment config via parameters (not hardcoded globals)",
    "inline-import-type": "Use top-level import type declarations (not inline import types)",
    "as-any": "Use proper types (not unsafe type casts)",
    "relative-import": "Use non-relative path aliases (not relative imports)",
  };

  sections.push("Coding Standards require:");
  for (const [category, fix] of Object.entries(fixMap)) {
    if (grouped[category]?.length) {
      sections.push(`  - ${fix}`);
    }
  }

  return sections.join("\n");
}

// ─── Contract ────────────────────────────────────────────────────────────────

const defaultDeps: CodingStandardsEnforcerDeps = {
  readFile: (path: string): string | null => {
    const result = adapterReadFile(path);
    return result.ok ? result.value : null;
  },
  signal: defaultSignalLoggerDeps,
  stderr: (msg) => process.stderr.write(msg + "\n"),
};

export const CodingStandardsEnforcer: HookContract<
  ToolHookInput,
  ContinueOutput | BlockOutput,
  CodingStandardsEnforcerDeps
> = {
  name: "CodingStandardsEnforcer",
  event: "PreToolUse",

  accepts(input: ToolHookInput): boolean {
    if (input.tool_name !== "Edit" && input.tool_name !== "Write") return false;
    const filePath = getFilePath(input);
    if (!filePath) return false;
    if (!isTypeScriptFile(filePath)) return false;
    if (isAdapterFile(filePath)) return false;
    if (isAutoGeneratedFile(filePath)) return false;
    if (isSkippedFilename(filePath)) return false;
    return true;
  },

  execute(
    input: ToolHookInput,
    deps: CodingStandardsEnforcerDeps,
  ): Result<ContinueOutput | BlockOutput, PaiError> {
    const filePath = getFilePath(input)!;

    // Determine the full file content that would exist after this operation
    let contentToCheck: string | null = null;

    if (input.tool_name === "Write") {
      // Write replaces the entire file — check the new content directly
      contentToCheck = getWriteContent(input);
    } else if (input.tool_name === "Edit") {
      // Edit is partial — read the current file, apply the edit, check the result
      const editParts = getEditParts(input);
      if (!editParts) {
        return ok({ type: "continue", continue: true });
      }

      const currentFile = deps.readFile(filePath);
      if (currentFile !== null) {
        // File exists: simulate the edit on the full file
        contentToCheck = applyEdit(currentFile, editParts.oldStr, editParts.newStr);
      } else {
        // File doesn't exist yet (new file via Edit, rare): check just new_string
        contentToCheck = editParts.newStr;
      }
    }

    if (!contentToCheck) {
      return ok({ type: "continue", continue: true });
    }

    const violations = findAllViolations(contentToCheck);

    if (violations.length === 0) {
      deps.stderr(`[CodingStandardsEnforcer] ${filePath}: clean`);
      return ok({ type: "continue", continue: true });
    }

    // Log violations for pattern analysis
    logSignal(deps.signal, "coding-standards-violations.jsonl", {
      session_id: input.session_id,
      hook: "CodingStandardsEnforcer",
      event: "PreToolUse",
      tool: input.tool_name,
      file: filePath,
      outcome: "block",
      violation_count: violations.length,
      violations: violations.map(v => ({
        category: v.category,
        line: v.line,
        content: v.content,
      })),
    });

    const message = formatBlockMessage(violations, filePath);
    deps.stderr(message);

    return ok({
      type: "block",
      decision: "block",
      reason: message,
    });
  },

  defaultDeps,
};
