/**
 * CodingStandardsAdvisor Contract — Warn about violations when files are read.
 *
 * PostToolUse hook that fires after Read operations on .ts/.tsx files.
 * Scans the file content for coding standard violations and injects
 * advisory context so the model knows to plan fixes BEFORE attempting edits.
 *
 * This is the "warn" side of the warn-then-enforce pattern:
 *   - CodingStandardsAdvisor (this) — PostToolUse Read → advises
 *   - CodingStandardsEnforcer        — PreToolUse Edit/Write → blocks
 *
 * Silent for clean files (zero context cost). Only injects additionalContext
 * when violations are found.
 *
 * Excludes adapter files (any adapters/ directory or adapter(s).ts files)
 * which legitimately wrap builtins.
 */

import type { SyncHookContract } from "@hooks/core/contract";
import type { ToolHookInput } from "@hooks/core/types/hook-inputs";
import type { ContinueOutput } from "@hooks/core/types/hook-outputs";
import { ok, type Result } from "@hooks/core/result";
import type { PaiError } from "@hooks/core/error";
import {
  findAllViolations,
  formatViolationSummary,
  isTypeScriptFile,
  isAdapterFile,
  isAutoGeneratedFile,
  isSkippedFilename,
} from "@hooks/lib/coding-standards-checks";
import { isSvelteFile, extractSvelteScript } from "@hooks/lib/svelte-utils";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface CodingStandardsAdvisorDeps {
  readFile: (path: string) => string | null;
  stderr: (msg: string) => void;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function getFilePath(input: ToolHookInput): string | null {
  if (typeof input.tool_input !== "object" || input.tool_input === null) return null;
  return (input.tool_input.file_path as string) ?? null;
}

// ─── Contract ────────────────────────────────────────────────────────────────

const defaultDeps: CodingStandardsAdvisorDeps = {
  readFile: (path: string): string | null => {
    const fs = require("fs");
    if (!fs.existsSync(path)) return null;
    return fs.readFileSync(path, "utf-8");
  },
  stderr: (msg) => process.stderr.write(msg + "\n"),
};

export const CodingStandardsAdvisor: SyncHookContract<
  ToolHookInput,
  ContinueOutput,
  CodingStandardsAdvisorDeps
> = {
  name: "CodingStandardsAdvisor",
  event: "PostToolUse",

  accepts(input: ToolHookInput): boolean {
    if (input.tool_name !== "Read") return false;
    const filePath = getFilePath(input);
    if (!filePath) return false;
    if (!isTypeScriptFile(filePath)) return false;
    if (isAdapterFile(filePath)) return false;
    if (isAutoGeneratedFile(filePath)) return false;
    if (isSkippedFilename(filePath)) return false;
    return true;
  },

  execute(
    input: ToolHookInput,
    deps: CodingStandardsAdvisorDeps,
  ): Result<ContinueOutput, PaiError> {
    const filePath = getFilePath(input)!;

    let content = deps.readFile(filePath);
    if (!content) {
      // File doesn't exist or can't be read — fail open, no advisory
      return ok({ type: "continue", continue: true });
    }

    // For Svelte files, only check the <script lang="ts"> block
    if (isSvelteFile(filePath)) {
      const scriptContent = extractSvelteScript(content);
      if (!scriptContent) {
        return ok({ type: "continue", continue: true });
      }
      content = scriptContent;
    }

    const violations = findAllViolations(content, filePath);

    if (violations.length === 0) {
      deps.stderr(`[CodingStandardsAdvisor] ${filePath}: clean`);
      return ok({ type: "continue", continue: true });
    }

    const advisory = formatViolationSummary(violations, filePath);
    deps.stderr(`[CodingStandardsAdvisor] ${filePath}: ${violations.length} violations found`);

    return ok({
      type: "continue",
      continue: true,
      additionalContext: advisory,
    });
  },

  defaultDeps,
};
