/**
 * SessionQualityReport Contract — Aggregate quality summary at session end.
 *
 * Reads stored baselines and final scores, generates a quality summary,
 * and writes it to MEMORY/LEARNING/QUALITY/{year}-{month}/.
 *
 * Output: SilentOutput (report written to disk, no stdout needed).
 */

import type { SyncHookContract } from "@hooks/core/contract";
import type { SessionEndInput } from "@hooks/core/types/hook-inputs";
import type { SilentOutput } from "@hooks/core/types/hook-outputs";
import { ok, type Result } from "@hooks/core/result";
import type { PaiError } from "@hooks/core/error";
import { fileExists, readFile, readJson, writeFile, ensureDir } from "@hooks/core/adapters/fs";
import { join } from "path";
import { getLocalComponents } from "@hooks/lib/time";

// ─── Types ───────────────────────────────────────────────────────────────────

interface BaselineEntry {
  score: number;
  violations: number;
  timestamp: string;
}

interface BaselineStore {
  [filePath: string]: BaselineEntry;
}

interface FileQualityChange {
  filePath: string;
  baselineScore: number;
  finalScore: number | null;
  delta: number | null;
}

export interface SessionQualityReportDeps {
  fileExists: (path: string) => boolean;
  readFile: (path: string) => Result<string, PaiError>;
  readJson: <T = unknown>(path: string) => Result<T, PaiError>;
  writeFile: (path: string, content: string) => Result<void, PaiError>;
  ensureDir: (path: string) => Result<void, PaiError>;
  getLocalComponents: typeof getLocalComponents;
  baseDir: string;
  stderr: (msg: string) => void;
}

// ─── Pure Logic ──────────────────────────────────────────────────────────────

function buildReport(
  baselines: BaselineStore,
  sessionId: string,
  time: ReturnType<typeof getLocalComponents>,
): string {
  const files = Object.entries(baselines);
  const fileSummaries: FileQualityChange[] = files.map(([filePath, entry]) => ({
    filePath,
    baselineScore: entry.score,
    finalScore: null,
    delta: null,
  }));

  const improved = fileSummaries.filter((f) => f.delta !== null && f.delta > 0);
  const degraded = fileSummaries.filter((f) => f.delta !== null && f.delta < 0);
  const unchanged = fileSummaries.filter((f) => f.delta === null || f.delta === 0);

  const avgScore = files.length > 0
    ? files.reduce((sum, [, e]) => sum + e.score, 0) / files.length
    : 0;

  const lines: string[] = [
    `# Session Quality Report`,
    ``,
    `**Session:** ${sessionId}`,
    `**Date:** ${time.year}-${time.month}-${time.day} ${time.hours}:${time.minutes} PST`,
    `**Files Baselined:** ${files.length}`,
    `**Average Score:** ${avgScore.toFixed(1)}/10`,
    ``,
    `## Files Analyzed`,
    ``,
  ];

  if (files.length === 0) {
    lines.push(`No source files were read during this session.`);
  } else {
    lines.push(`| File | Score | Violations |`);
    lines.push(`|------|-------|------------|`);
    for (const [filePath, entry] of files.sort((a, b) => a[1].score - b[1].score)) {
      const name = filePath.split("/").pop() ?? filePath;
      lines.push(`| ${name} | ${entry.score}/10 | ${entry.violations} |`);
    }
  }

  lines.push(``);
  lines.push(`## Summary`);
  lines.push(``);

  if (files.length > 0) {
    const lowScore = files.filter(([, e]) => e.score < 6);
    if (lowScore.length > 0) {
      lines.push(`### Files Needing Attention`);
      for (const [filePath, entry] of lowScore) {
        lines.push(`- **${filePath.split("/").pop()}** (${entry.score}/10): ${entry.violations} violations`);
      }
      lines.push(``);
    }

    const highScore = files.filter(([, e]) => e.score >= 8);
    if (highScore.length > 0) {
      lines.push(`### Clean Files`);
      for (const [filePath, entry] of highScore) {
        lines.push(`- **${filePath.split("/").pop()}** (${entry.score}/10)`);
      }
      lines.push(``);
    }
  }

  lines.push(`---`);
  lines.push(`*Auto-generated by SessionQualityReport*`);

  return lines.join("\n");
}

// ─── Contract ────────────────────────────────────────────────────────────────

const BASE_DIR = process.env.PAI_DIR || join(process.env.HOME!, ".claude");

const defaultDeps: SessionQualityReportDeps = {
  fileExists,
  readFile,
  readJson,
  writeFile,
  ensureDir,
  getLocalComponents,
  baseDir: BASE_DIR,
  stderr: (msg) => process.stderr.write(msg + "\n"),
};

export const SessionQualityReport: SyncHookContract<
  SessionEndInput,
  SilentOutput,
  SessionQualityReportDeps
> = {
  name: "SessionQualityReport",
  event: "SessionEnd",

  accepts(input: SessionEndInput): boolean {
    return !!input.session_id;
  },

  execute(
    input: SessionEndInput,
    deps: SessionQualityReportDeps,
  ): Result<SilentOutput, PaiError> {
    const baselinePath = join(deps.baseDir, "MEMORY", "STATE", `quality-baselines-${input.session_id}.json`);

    if (!deps.fileExists(baselinePath)) {
      deps.stderr("[SessionQualityReport] No quality baselines found, skipping");
      return ok({ type: "silent" });
    }

    const storeResult = deps.readJson<BaselineStore>(baselinePath);
    if (!storeResult.ok) {
      deps.stderr("[SessionQualityReport] Could not read baselines, skipping");
      return ok({ type: "silent" });
    }

    const baselines = storeResult.value;
    if (Object.keys(baselines).length === 0) {
      deps.stderr("[SessionQualityReport] Empty baselines, skipping");
      return ok({ type: "silent" });
    }

    const time = deps.getLocalComponents();
    const report = buildReport(baselines, input.session_id, time);

    const qualityDir = join(deps.baseDir, "MEMORY", "LEARNING", "QUALITY", `${time.year}-${time.month}`);
    deps.ensureDir(qualityDir);

    const filename = `quality-${time.year}${time.month}${time.day}-${time.hours}${time.minutes}.md`;
    const reportPath = join(qualityDir, filename);

    deps.writeFile(reportPath, report);
    deps.stderr(`[SessionQualityReport] Report written to ${reportPath}`);

    return ok({ type: "silent" });
  },

  defaultDeps,
};
