/**
 * CodingStandardsAdvisor Contract — Warn about violations when files are read.
 *
 * PostToolUse hook that fires after Read operations on .ts/.tsx files.
 * Scans the file content for coding standard violations and injects
 * advisory context so the model knows to plan fixes BEFORE attempting edits.
 *
 * This is the "warn" side of the warn-then-enforce pattern:
 *   - CodingStandardsAdvisor (this) — PostToolUse Read → advises
 *   - CodingStandardsEnforcer        — PreToolUse Edit/Write → blocks
 *
 * Silent for clean files (zero context cost). Only injects additionalContext
 * when violations are found.
 *
 * Excludes adapter files (any adapters/ directory or adapter(s).ts files)
 * which legitimately wrap builtins.
 */

import type { SyncHookJSONOutput } from "@anthropic-ai/claude-agent-sdk";
import { readFile as adapterReadFile } from "@hooks/core/adapters/fs";
import type { SyncHookContract } from "@hooks/core/contract";
import type { ResultError } from "@hooks/core/error";
import { ok, type Result } from "@hooks/core/result";
import type { ToolHookInput } from "@hooks/core/types/hook-inputs";
import {
  findAllViolations,
  formatViolationSummary,
  isAdapterFile,
  isAutoGeneratedFile,
  isSkippedFilename,
  isTypeScriptFile,
} from "@hooks/lib/coding-standards-checks";
import { defaultStderr } from "@hooks/lib/paths";
import { extractSvelteScript, isSvelteFile } from "@hooks/lib/svelte-utils";
import { getFilePath } from "@hooks/lib/tool-input";

// ─── Types ───────────────────────────────────────────────────────────────────

export interface CodingStandardsAdvisorDeps {
  readFile: (path: string) => string | null;
  stderr: (msg: string) => void;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

// ─── Contract ────────────────────────────────────────────────────────────────

const defaultDeps: CodingStandardsAdvisorDeps = {
  readFile: (path: string): string | null => {
    const result = adapterReadFile(path);
    return result.ok ? result.value : null;
  },
  stderr: defaultStderr,
};

export const CodingStandardsAdvisor: SyncHookContract<ToolHookInput, CodingStandardsAdvisorDeps> = {
  name: "CodingStandardsAdvisor",
  event: "PostToolUse",

  accepts(input: ToolHookInput): boolean {
    if (input.tool_name !== "Read") return false;
    const filePath = getFilePath(input);
    if (!filePath) return false;
    if (!isTypeScriptFile(filePath)) return false;
    if (isAdapterFile(filePath)) return false;
    if (isAutoGeneratedFile(filePath)) return false;
    if (isSkippedFilename(filePath)) return false;
    return true;
  },

  execute(
    input: ToolHookInput,
    deps: CodingStandardsAdvisorDeps,
  ): Result<SyncHookJSONOutput, ResultError> {
    const filePath = getFilePath(input)!;

    let content = deps.readFile(filePath);
    if (!content) {
      // File doesn't exist or can't be read — fail open, no advisory
      return ok({ continue: true });
    }

    // For Svelte files, only check the <script lang="ts"> block
    if (isSvelteFile(filePath)) {
      const scriptContent = extractSvelteScript(content);
      if (!scriptContent) {
        return ok({ continue: true });
      }
      content = scriptContent;
    }

    const violations = findAllViolations(content, filePath);

    if (violations.length === 0) {
      deps.stderr(`[CodingStandardsAdvisor] ${filePath}: clean`);
      return ok({ continue: true });
    }

    const advisory = formatViolationSummary(violations, filePath);
    deps.stderr(`[CodingStandardsAdvisor] ${filePath}: ${violations.length} violations found`);

    // R2: PostToolUse advisory context injection via hookSpecificOutput.additionalContext.
    // Post-SDK-refactor, fixes a bug where the legacy top-level `additionalContext` from
    // `continueOk(advisory)` was silently dropped for PostToolUse events — the SDK canonical
    // channel for PostToolUse context injection is hookSpecificOutput.additionalContext.
    return ok({
      continue: true,
      hookSpecificOutput: {
        hookEventName: "PostToolUse",
        additionalContext: advisory,
      },
    });
  },

  defaultDeps,
};
